# --- Force le backend à écouter UNIQUEMENT sur HTTPS (port 8443) ---
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=mes-local

spring.application.name=backend
# Nom de l’application (utile pour Actuator, logs, etc.)

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Active la console web H2 sur /h2-console

# Utilise une base H2 persistante, chiffrée avec AES, dans ./data/mesdb
spring.datasource.url=jdbc:h2:file:./data/mesdb;CIPHER=AES
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
# Mot de passe H2 chiffrée : <mot_de_passe_fichier> <mot_de_passe_jdbc>
spring.datasource.password=motdepassefort sa

spring.datasource.initialization-mode=always
# Initialise le schéma à chaque lancement (pratique en dev)

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Affiche les requêtes SQL dans la console (debug)